version: "3"
services:
  backend:
    build: "./backend"
    container_name: "pa-be"
    image: node:latest
    restart: unless-stopped
    environment:
      DATABASE_HOST: host.docker.internal
    ports:
      - 1337:1337
    command: "npm start"

  frontend:
    build:
      context: "./frontend"
    ports:
      - "3000:3000"
    container_name: pa-fe
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
