version: "3"

services:
  nginx:
    container_name: "pa-nginx"
    depends_on:
      - backend
      - database
    restart: always
    build:
      dockerfile: "Dockerfile"
      context: "./nginx"
    ports:
      - "3050:80"
  database:
    env_file: "./.env"
    container_name: "pa-db"
    image: "postgres:15-alpine"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_HOST: host.docker.internal
      NODE_ENV: "production"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  backend:
    env_file: "./.env"
    container_name: "pa-be"
    depends_on:
      database:
        condition: service_healthy
    build:
      context: "./backend"
      dockerfile: "./Dockerfile"
      args:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        PORT: "${PORT}"
        NODE_ENV: "production"
    image: node:latest-alpine
    restart: unless-stopped
    ports:
      - "3010:3010"
    command: "npm start"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: host.docker.internal
      PORT: "${PORT}"
      GOOGLE_PLUS_CLIENT_ID: ${GOOGLE_PLUS_CLIENT_ID}
      GOOGLE_PLUS_CLIENT_SECRET: ${GOOGLE_PLUS_CLIENT_SECRET}
      NODE_ENV: "production"

  frontend:
    container_name: pa-fe
    depends_on:
      - backend
    build:
      context: "./frontend"
    environment:
      REACT_APP_BASE_URL: "${REACT_APP_BASE_URL}"
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules

volumes:
  database:
